I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 97, in script
    $ flag_1 = Test
  File "game/script.rpy", line 97, in <module>
    $ flag_1 = Test
NameError: name 'Test' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 97, in script
    $ flag_1 = Test
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 97, in <module>
    $ flag_1 = Test
NameError: name 'Test' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
TitleTentative 1.0
Tue Jul 06 23:07:03 2021
